name: Build, test and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
      - name: Install NPM modules
        run: npm install
      - name: Replace the BackEnd end-point
        run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
      - name: Start the BackEnd
        run: npm run start-be &
      - name: Start the FrontEnd
        run: npm run start-fe &
      - name: Install Browsers
        run: npx playwright install
      - name: Execute the UI tests
        run: npm run test:ui

  deploy-fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.API_RENDER_FE_KEY }}
          api_key: ${{ secrets.API_RENDER_KEY }}

  deploy-be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.API_RENDER_BE_KEY }}
          api_key: ${{ secrets.API_RENDER_KEY }}
